name: image_painter
description: A flutter package for drawing over images. Supports color,
  strokeWidth, different paintModes and exporting image.
version: 0.4.5
homepage: https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1
  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_lints: ^1.0.4

